Portal/Controllers/StudentFoodPacketController.cs
using Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Portal.Models;

namespace Portal.Controllers;

[Authorize(Policy = "Student")]
public class StudentFoodPacketController : Controller
{
    private readonly IFoodPacketRepository _foodPacketRepository;
    private readonly ILogger<StudentFoodPacketController> _logger;
    private readonly IStudentRepository _studentRepository;
    private readonly UserManager<IdentityUser> _userManager;

    public StudentFoodPacketController(ILogger<StudentFoodPacketController> logger,
        IFoodPacketRepository foodPacketRepository,
        UserManager<IdentityUser> userManager, IStudentRepository studentRepository)
    {
        _logger = logger;
        _foodPacketRepository = foodPacketRepository;
        _userManager = userManager;
        _studentRepository = studentRepository;
    }

    public async Task<ViewResult> Index()
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);
        var student = _studentRepository.GetStudentByEmail(user.Email);
        var foodPackets = _foodPacketRepository.GetAllFoodPackets().ToList();
        var studentReservations = foodPackets.Where(p => p.ReservedBy == student).ToList();

        if (TempData["PacketIsReserved"] != null)
        {
            ViewBag.PacketIsReserved = TempData["PacketIsReserved"];
            TempData.Clear();
        }

        return View(new StudentIndexViewModel
        {
            FoodPackets = _foodPacketRepository.GetAllFoodPackets()
                .Where(fp => fp.ReservedBy == null),
            User = student,
            UserAgePlus18 = student.Birthday.AddYears(18),
            UserReservations = studentReservations
        });
    }

    public async Task<ViewResult> ReservedPackets()
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);
        var reservedPackets = _foodPacketRepository.GetAllFoodPackets()
            .Where(fp => fp.ReservedBy?.EmailAddress == user.Email);
        return View(reservedPackets);
    }

    public async Task<RedirectToActionResult> ReserveFoodPacket(int id)
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);
        var student = _studentRepository.GetStudentByEmail(user.Email);
        var foodPacket = _foodPacketRepository.GetFoodPacketById(id);
        if (foodPacket.ReservedBy != null)
        {
            TempData["PacketIsReserved"] = "Apologies, but this packet has since been reserved by another student";
            return RedirectToAction("Index");
        }

        _foodPacketRepository.SetReservation(foodPacket, student);
        return RedirectToAction("Index");
    }

    public RedirectToActionResult CancelFoodPacketReservation(int id)
    {
        var foodPacket = _foodPacketRepository.GetFoodPacketById(id);
        _foodPacketRepository.ClearReservation(foodPacket);
        return RedirectToAction("ReservedPackets");
    }

    public ViewResult ViewFoodPacketDetails(int id)
    {
        var foodPacket = _foodPacketRepository.GetFoodPacketById(id);
        return View(foodPacket);
    }
}

Portal/Controllers/StudentProductController.cs
using Core.DomainServices;
using Microsoft.AspNetCore.Mvc;
using Portal.Models;

namespace Portal.Controllers;

public class StudentProductController : Controller
{
    private readonly IProductRepository _productRepository;

    public StudentProductController(IProductRepository productRepository)
    {
        _productRepository = productRepository;
    }

    public ViewResult ViewProductDetails(int id)
    {
        var product = _productRepository.GetProductById(id);
        var displayProductViewModel = new DisplayProductViewModel
        {
            Name = product.Name,
            Alcoholic = product.Alcoholic
        };
        if (product.ProfilePicture != null)
            displayProductViewModel.ProfilePicture = Convert.ToBase64String(product.ProfilePicture);
        else product.ProfilePicture = null;
        displayProductViewModel.PictureFormat = product.PictureFormat;
        return View(displayProductViewModel);
    }
}

Portal/Views/StudentFoodPacket/Index.cshtml
@model StudentIndexViewModel

<div>
    @if (ViewBag.PacketIsReserved != null)
    {
        <p>@ViewBag.PacketIsReserved</p>
    }
    <a asp-action="ReservedPackets" class="btn btn-primary">View my reserved packets</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <th colspan="8">Available packets</th>
        </tr>
        <th>Name</th>
        <th>City</th>
        <th>Cafeteria</th>
        <th>Pickup time</th>
        <th>Pickup expiration time</th>
        <th>18+</th>
        <th>Price</th>
        @* <th>Meal type</th> *@
        <th>Reserve packet</th>
        </thead>
        <tbody>
        @foreach (var fp in Model.FoodPackets)
        {
            <tr>
                <td>
                    <a asp-action="ViewFoodPacketDetails" asp-controller="StudentFoodPacket" asp-route-id="@fp.Id">@fp.Name</a>
                </td>
                <td>@fp.City</td>
                <td>@fp.Location</td>
                <td>@fp.PickupTime</td>
                <td>@fp.PickupExpirationTime</td>
                @if ((bool) fp.Is18Plus)
                {
                    <td>Yes</td>
                }
                else
                {
                    <td>No</td>
                }
                <td>@fp.Price</td>
                @* <td>@fp.MealType</td> *@
                <td>
                    @if (!Model.IsReservationThatDay(fp) // check that user has not reserved a packet that day
                         && (fp.Is18Plus == false
                             || (fp.Is18Plus == true && Model.UserAgePlus18.Date <= fp.PickupTime.Value.Date))) // check that user is 18 if packet is 18+
                    {
                        <a asp-action="ReserveFoodPacket" asp-controller="StudentFoodPacket" asp-route-id="@fp.Id">Reserve</a>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

Portal/Views/StudentFoodPacket/ReservedPackets.cshtml
@model IEnumerable<Core.Domain.FoodPacket>

<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="StudentFoodPacket">Back</a>
    <table class="table table-striped">
        <thead>
        <th>Name</th>
        <th>City</th>
        <th>Cafeteria</th>
        <th>Pickup time</th>
        <th>Pickup expiration time</th>
        <th>18+</th>
        <th>Price</th>
        <th>Meal type</th>
        <th>Cancel reservation</th>
        </thead>
        <tbody>
        @foreach (var fp in Model)
        {
            <tr>
                <td>
                    <a asp-action="ViewFoodPacketDetails" asp-controller="StudentFoodPacket" asp-route-id="@fp.Id">@fp.Name</a>
                </td>
                <td>@fp.City</td>
                <td>@fp.Location</td>
                <td>@fp.PickupTime</td>
                <td>@fp.PickupExpirationTime</td>
                @if ((bool) fp.Is18Plus)
                {
                    <td>Yes</td>
                }
                else
                {
                    <td>No</td>
                }
                <td>@fp.Price</td>
                <td>@fp.MealType</td>
                <td>
                    <a asp-action="CancelFoodPacketReservation" asp-controller="StudentFoodPacket" asp-route-id="@fp.Id">Cancel</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

Portal/Views/StudentFoodPacket/ViewFoodPacketDetails.cshtml
@model Core.Domain.FoodPacket

<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="StudentFoodPacket">Back</a>
    <h2>@Model.Name</h2>
    <hr/>
    <h4>General information about this packet:</h4>
    <table class="table table-striped">
        <thead>
        <th>City</th>
        <th>Location</th>
        <th>Price</th>
        <th>Contains alcohol</th>
        <th>Pickup time</th>
        <th>Pickup expiration time</th>
        </thead>
        <tbody>
        <tr>
            <td>@Model.City</td>
            <td>@Model.Location</td>
            <td>@Model.Price</td>
            @if ((bool) @Model.Is18Plus)
            {
                <td>Yes</td>
            }
            else
            {
                <td>No</td>
            }
            <td>@Model.PickupTime</td>
            <td>@Model.PickupExpirationTime</td>
        </tr>
        </tbody>
    </table>

    <h4>Products in this packet:</h4>
    <ul>
        @foreach (var product in Model.Products)
        {
            <li>
                <a asp-action="ViewProductDetails" asp-controller="StudentProduct" asp-route-id="@product.Id">@product.Name</a>
            </li>
        }
    </ul>
</div>